#include <fstream>
#include <iostream>

#include "ap_fixed.h"

typedef ap_fixed<16, 2> sample_t;
typedef ap_ufixed<16, 12> step_t;

void nco(sample_t *sine_sample, step_t step_size);

int main()
{
    const char *outfile = "nco_sine.m";
    std::ofstream fout(outfile);

    if (!fout) {
        std::cout << "Cannot open output file." << std::endl;
        return 1;
    }

    sample_t sample;
    step_t step_size = 256.0;

    fout << "% Generated by Vitis HLS C simulation" << std::endl;
    fout << "y = zeros(1,64);" << std::endl;

    for (int i = 0; i < 64; i++) {
        nco(&sample, step_size);
        fout << "y(" << (i + 1) << ") = " << sample.to_double() << ";" << std::endl;
    }

    fout << "plot(y); grid on; title('NCO output');" << std::endl;
    fout.close();

    std::cout << "Sample output to file complete: " << outfile << std::endl;
    return 0;
}
